### ISSUE TITLE
Compile failed with nginx-0.8.53

### ISSUE THREAD

**Issue by nightsailer** [brianpane/jitify-core#1]
OS: SnowLeopard 10.6.5 64bit
Nginx-0.8.53
gcc version 4.2.1 (Apple Inc. build 5664)

./configure --prefix=/opt/nginx \
--add-module=../jitify-core/src/nginx 

Error:

gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Wunused-function -Wunused-variable -Wunused-value -Werror -g  -Werror -Wall -I../jitify-core/src/nginx -I../jitify-core/src/nginx/../core -I src/core -I src/event -I src/event/modules -I src/os/unix -I /opt/local/include -I objs \
                -o objs/src/core/nginx.o \
                src/core/nginx.c
cc1: warnings being treated as errors
src/core/nginx.c: In function ‘ngx_set_user’:
src/core/nginx.c:1101: warning: unused parameter ‘cmd’
src/core/nginx.c: In function ‘ngx_set_env’:
src/core/nginx.c:1164: warning: unused parameter ‘cmd’
src/core/nginx.c: In function ‘ngx_set_priority’:
src/core/nginx.c:1194: warning: unused parameter ‘cmd’
src/core/nginx.c: In function ‘ngx_set_cpu_affinity’:
src/core/nginx.c:1234: warning: unused parameter ‘cmd’
src/core/nginx.c:1234: warning: unused parameter ‘conf’
make[1]: **\* [objs/src/core/nginx.o] Error 1
make: **\* [build] Error 2

**Comment by brianpane** [comment]
Sorry about that; I need to remove the -Wall from the compiler argument string in Jitify's config.make, because it ends up following - and thus overriding - the -Wno-unused-parameter that's required to make recent versions of nginx compile.  I'll push out a fix shortly.

**Comment by brianpane** [comment]
I just pushed a few code fixes for compatibility with newer nginx versions.  You can sink from github or get the jitify-core-0.9.2 source distribution from www.jitify.com.
